FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

# Убедитесь, что vite.config.js скопирован
COPY vite.config.js .

CMD ["yarn", "dev", "--host", "0.0.0.0"]